# This is a basic workflow to help you get started with Actions

name: Style check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 7 * * 1"

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "style-check"
  style-check:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.2.2

      # Runs a single command using the runners shell
      - name: Brew Update
        run: |
          brew update
          brew --version

      - name: Setup Homebrew Tap
        run: |
          mkdir -p /opt/homebrew/Library/Taps/KingsleyLeung03/homebrew-cask-upgrade-oc
          cp -rf . /opt/homebrew/Library/Taps/KingsleyLeung03/homebrew-cask-upgrade-oc

      - name: Style check
        run: brew style --display-cop-names KingsleyLeung03/homebrew-cask-upgrade-oc
